spring:
  application:
    name: jrebel-license-server
  freemarker:
    enabled: true
    prefix: /
    suffix: .ftl
    template-loader-path: classpath:/templates/
  mvc:
    static-path-pattern: /**
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web: INFO
    com.imjcker.jrebel: DEBUG
  file:
    name: ${user.home}/logs/jrebel.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB

server:
  port: 8282

jrebel:
  url-cn: https://jrebel.imjcker.com:1314
  url-global: https://jrebel.hk.imjcker.com
  social:
    - name: CSDN
      url: https://blog.csdn.net/u012137018
    - name: 博客园
      url: https://www.cnblogs.com/tfsc/
    - name: GitHub
      url: https://github.com/everydoc
    - name: 个人博客
      url: https://blog.hk.imjcker.com
